spring:
  application:
    name: qlc-backend
  profiles:
    active: dev
  data: 
    redis:
      host: localhost
      port: 6379

  jackson:
    default-property-inclusion: non_null

app:
  submissions:
    max-size: 65535
    max-log-length: 10000
    stream-name: "qlc:submissions"
    worker:
      enabled: true
      consumer-group: "submission-workers"
      consumer-name: "${WORKER_ID:qlc-worker-1}"
      poll-delay-ms: 500
      batch-size: 10
